"""Google OAuth 2.0 integration.

Google is used ONLY to prove the user's identity (who they are). Google
must never determine the user's role, which is why both verify_google_token()
and exchange_code_for_identity() return only identity fields — there is
deliberately no way for a role to come out of this module.

Two ways to obtain a verified identity:

- verify_google_token(token): verifies a Google ID token obtained by the
  client (used by the POST /auth/google API endpoint).
- build_google_auth_url(state) + exchange_code_for_identity(code): the
  server-side OAuth 2.0 redirect flow (browser login). The client secret
  is used ONLY here, on the backend, and is never exposed to the browser.
"""

import os
from urllib.parse import urlencode

import requests
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token

# The OAuth 2.0 client ID of this application (Google Cloud Console).
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
# The OAuth 2.0 client secret. BACKEND ONLY — never send it to the browser.
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")
# Must match an "Authorized redirect URI" of the OAuth client in Google Cloud Console.
GOOGLE_REDIRECT_URI = os.environ.get(
    "GOOGLE_REDIRECT_URI", "http://localhost:5000/auth/google/callback"
)

GOOGLE_AUTH_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_SCOPES = "openid email profile"


def verify_google_token(token: str) -> dict:
    """Verify a Google ID token and return the user's identity.

    Returns a dict with only: sub, email, name.
    Raises ValueError if the token is invalid or expired.
    """
    if not GOOGLE_CLIENT_ID:
        raise ValueError("GOOGLE_CLIENT_ID is not configured")
    try:
        info = id_token.verify_oauth2_token(
            token, google_requests.Request(), GOOGLE_CLIENT_ID
        )
    except ValueError as exc:
        raise ValueError("Invalid Google token") from exc

    # Only identity fields are taken from Google. Never a role.
    return {
        "sub": info["sub"],
        "email": info.get("email", ""),
        "name": info.get("name", ""),
    }


def build_google_auth_url(state: str) -> str:
    """Build the Google consent-screen URL that starts the redirect flow.

    "state" is a random CSRF token generated by the backend; Google returns
    it untouched to the callback, which must compare it before proceeding.
    Raises ValueError if GOOGLE_CLIENT_ID is not configured.
    """
    if not GOOGLE_CLIENT_ID:
        raise ValueError("GOOGLE_CLIENT_ID is not configured")
    params = {
        "client_id": GOOGLE_CLIENT_ID,
        "redirect_uri": GOOGLE_REDIRECT_URI,
        "response_type": "code",
        "scope": GOOGLE_SCOPES,
        "state": state,
        "access_type": "online",
        "prompt": "select_account",
    }
    return f"{GOOGLE_AUTH_ENDPOINT}?{urlencode(params)}"


def exchange_code_for_identity(code: str) -> dict:
    """Exchange an authorization code for the user's identity.

    This is the ONLY place the client secret is used: the code exchange
    happens server-to-server, so the secret never reaches the browser.
    Returns the same identity dict as verify_google_token().
    Raises ValueError if the exchange fails or the ID token is invalid.
    """
    if not GOOGLE_CLIENT_SECRET:
        raise ValueError("GOOGLE_CLIENT_SECRET is not configured")
    try:
        response = requests.post(
            GOOGLE_TOKEN_ENDPOINT,
            data={
                "code": code,
                "client_id": GOOGLE_CLIENT_ID,
                "client_secret": GOOGLE_CLIENT_SECRET,
                "redirect_uri": GOOGLE_REDIRECT_URI,
                "grant_type": "authorization_code",
            },
            timeout=10,
        )
    except requests.RequestException as exc:
        raise ValueError("Google token exchange failed") from exc
    if response.status_code != 200:
        raise ValueError("Google token exchange failed")

    id_token_value = response.json().get("id_token")
    if not id_token_value:
        raise ValueError("Google token exchange failed")

    # Same verification (signature, expiry, audience) as the API flow.
    return verify_google_token(id_token_value)
