"""Google OAuth 2.0 integration.

Google is used ONLY to prove the user's identity (who they are). Google
must never determine the user's role, which is why both verify_google_token()
and exchange_code_for_identity() return only identity fields — there is
deliberately no way for a role to come out of this module.

Two ways to obtain a verified identity:

- verify_google_token(token): verifies a Google ID token obtained by the
  client (used by the POST /auth/google API endpoint).
- build_google_auth_url(state) + exchange_code_for_identity(code): the
  server-side OAuth 2.0 redirect flow (browser login). The client secret
  is used ONLY here, on the backend, and is never exposed to the browser.
"""

import requests
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token

import config

GOOGLE_AUTH_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_SCOPES = "openid email profile"


def verify_google_token(token: str) -> dict:
    """Verify a Google ID token and return the user's identity.

    Returns a dict with only: sub, email, name, picture (profile photo URL,
    or None if the Google account has none).
    Raises ValueError if the token is invalid or expired.

    ``email_verified`` is enforced here rather than trusted implicitly: Google
    sets it false for accounts whose address has not been confirmed, and an
    unverified address would otherwise let anyone claim someone else's login.
    """
    if not config.GOOGLE_CLIENT_ID:
        raise ValueError("GOOGLE_CLIENT_ID is not configured")
    try:
        info = id_token.verify_oauth2_token(
            token, google_requests.Request(), config.GOOGLE_CLIENT_ID
        )
    except ValueError as exc:
        raise ValueError("Invalid Google token") from exc

    if not info.get("email_verified"):
        raise ValueError("Google email is not verified")

    email = (info.get("email") or "").strip().lower()
    if not email:
        raise ValueError("Google account has no email")

    # Only identity fields are taken from Google. Never a role.
    return {
        "sub": info["sub"],
        "email": email,
        "name": (info.get("name") or "").strip() or email.split("@")[0],
        "picture": info.get("picture"),
    }


def build_google_auth_url(state: str) -> str:
    """Build the Google consent-screen URL that starts the redirect flow.

    "state" is a random CSRF token generated by the backend; Google returns
    it untouched to the callback, which must compare it before proceeding.
    Raises ValueError if GOOGLE_CLIENT_ID is not configured.
    """
    if not config.GOOGLE_CLIENT_ID:
        raise ValueError("GOOGLE_CLIENT_ID is not configured")
    params = {
        "client_id": config.GOOGLE_CLIENT_ID,
        "redirect_uri": config.GOOGLE_REDIRECT_URI,
        "response_type": "code",
        "scope": GOOGLE_SCOPES,
        "state": state,
        "access_type": "online",
        "prompt": "select_account",
    }
    return f"{GOOGLE_AUTH_ENDPOINT}?{urlencode(params)}"


def exchange_code_for_identity(code: str) -> dict:
    """Exchange an authorization code for the user's identity.

    This is the ONLY place the client secret is used: the code exchange
    happens server-to-server, so the secret never reaches the browser.
    Returns the same identity dict as verify_google_token().
    Raises ValueError if the exchange fails or the ID token is invalid.
    """
    if not config.GOOGLE_CLIENT_SECRET:
        raise ValueError("GOOGLE_CLIENT_SECRET is not configured")
    if not config.GOOGLE_CLIENT_ID:
        raise ValueError("GOOGLE_CLIENT_ID is not configured")

    try:
        response = requests.post(
            GOOGLE_TOKEN_ENDPOINT,
            data={
                "code": code,
                "client_id": config.GOOGLE_CLIENT_ID,
                "client_secret": config.GOOGLE_CLIENT_SECRET,
                "redirect_uri": config.GOOGLE_REDIRECT_URI,
                "grant_type": "authorization_code",
            },
            timeout=10,
        )
    except requests.RequestException as exc:
        raise ValueError("Google token exchange failed") from exc

    if response.status_code != 200:
        # Google's error body explains the real cause, e.g.:
        # - invalid_grant        -> the code was already used or expired
        # - redirect_uri_mismatch -> GOOGLE_REDIRECT_URI doesn't match the console
        # - invalid_client       -> wrong/rotated GOOGLE_CLIENT_SECRET
        raise ValueError(
            f"Google token exchange failed: {response.status_code} {response.text}"
        )

    # Google reports a user-declined consent as HTTP 400 with a JSON error
    # body, so reading .json() safely matters: an HTML error page from a proxy
    # in front of Google must not raise an unhandled ValueError here.
    try:
        payload = response.json()
    except ValueError as exc:
        raise ValueError("Google token exchange failed") from exc
    if not isinstance(payload, dict):
        raise ValueError("Google token exchange failed")

    id_token_value = payload.get("id_token")
    if not id_token_value:
        raise ValueError("Google token exchange failed")

    # Same verification (signature, expiry, audience, email_verified) as the
    # API flow.
    return verify_google_token(id_token_value)
